apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jsjs22lee/aws9h.git
    targetRevision: HEAD
    path: shop
  destination:
    server: https://kubernetes.default.svc
    namespace: aws9h
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
