---
apiVersion: v1
kind: Service
metadata:
  name: aws9-service
spec:
  selector:
    color: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: shop-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      color: blue  # 나는 이러한 key: value 를 갖는 Pod 를 3개 유지할게!!! (controller가 담당)
  template:       # 실제적인 Pod 의 구성 정보
    metadata:
      labels:
        color: blue
    spec:
      containers:
        - name: shop-ctn
          image: nignx
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
            requests:
              memory: "32Mi"
              cpu: "250m"
          volumeMounts:
            - name: shopvol
              mountPath: /usr/share/nginx/html
          volumes:
            - name: shopvol
          persistentVolumeClaim:
             claimName: shop-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shop-pv
spec:
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs1
  nfs:
    path: /shared/shop
    server: 211.183.3.98
