apiVersion: v1
kind: Service
metadata:
  name: shop-service
  namespace: aws9h
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deploy
  namespace: aws9h
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop 
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop-ctn
          image: nginx
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
            requests:
              memory: "32Mi"
              cpu: "250m"
          volumeMounts:
            - name: shopvol
              mountPath: /usr/share/nginx/html
      volumes:
        - name: shopvol
          persistentVolumeClaim:
            claimName: shop-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-pvc
  namespace: aws9h
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: aws9h-storage

