---
apiVersion: v1
kind: Service
metadata:
  name: shop-svc
  namespace: aws9h
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Depolyment
metadata:
  name: shop-deploy
  namespace: aws9h
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop 
  template:
    metadata:
    spec:
      containers:
        - name: shop-ctn
          image: nignx
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
            requests:
              memory: "32Mi"
              cpu: "250m"
          volumeMounts:
            - name: shopvol
              mountPath: /usr/share/nginx/html
              subPath: shop #share 밑 shop 디렉토리 매핑
      volumes:
        - name: shopvol
          persistentVolumeClaim:
            claimName: shop-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-pvc
  namespace: aws9h
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: aws9h-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shop-pv
  namespace: aws9h
spec:
  capacity:
    storage: 1Gi
  accessModes: 
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws9h-storage
  nfs:
    path: /shared/shop
    server: 211.183.3.98
