apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: news-pvc
  namespace: aws9h
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: aws9h-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-deploy
  namespace: aws9h
spec:
  replicas: 3
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
      - name: news-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: news-volume
          mountPath: /usr/share/nginx/html/news-data
          subPath: news   # 💡 핵심! news 디렉토리 하위에 mount
      volumes:
      - name: news-volume
        persistentVolumeClaim:
          claimName: news-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: news-service
  namespace: aws9h
spec:
  selector:
    app: news
  ports:
    - port: 80
      targetPort: 80
