---
apiVersion: v1
kind: Service
metadata:
  name: aws9-service
spec:
  selector:
    color: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9-deploy-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      color: blue  # 나는 이러한 key: value 를 갖는 Pod 를 3개 유지할게!!! (controller가 담당)
  template:       # 실제적인 Pod 의 구성 정보
    metadata:
      labels:
        color: blue
    spec:
      containers:
        - name: aws9-ctn-blue
          image: brian24/aws9:blue
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
            requests:
              memory: "32Mi"
              cpu: "250m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aws9-hpa
spec:
  maxReplicas: 30
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aws9-deploy-blue
  targetCPUUtilizationPercentage: 40
---
root@master:~/lab0416# cat mypvc.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs1
