---
apiVersion: v1
kind: Service
metadata:
  name: aws9h-blog
  namespace: aws9h
spec:
  selector:
    tag: blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9-deploy-blog
  namespace: aws9h
spec:
  replicas: 3
  selector:
    matchLabels:
      tag: blog
  template:
    metadata:
      labels:
        tag: blog
    spec:
      containers:
        - name: aws9-ctn-blog
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
          - name: myvol
            mountPath: /usr/share/nginx/html
      volumes:
        - name: myvol
          persistentVolumeClaim:
            claimName: mypvc
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aws9-hpa
  namespace: aws9h
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aws9-deploy-blog
  targetCPUUtilizationPercentage: 60
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: aws9h
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: aws9h-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws9h-storage
mountOptions:
  - nfsvers=4.2
parameters:
  server: 211.183.3.98
  share: /shared/blog
provisioner: nfs.csi.k8s.io
reclaimPolicy: Delete 